# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\iojkp\OneDrive\桌面\NN2\110522160_劉秉澤_作業二\RBFN.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 732)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(130, 20, 481, 461))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(110, 550, 211, 61))
        self.groupBox.setObjectName("groupBox")
        self.radio4d = QtWidgets.QRadioButton(self.groupBox)
        self.radio4d.setGeometry(QtCore.QRect(20, 40, 98, 19))
        self.radio4d.setChecked(True)
        self.radio4d.setObjectName("radio4d")
        self.radio6d = QtWidgets.QRadioButton(self.groupBox)
        self.radio6d.setGeometry(QtCore.QRect(110, 40, 98, 19))
        self.radio6d.setObjectName("radio6d")
        self.Train = QtWidgets.QPushButton(self.centralwidget)
        self.Train.setGeometry(QtCore.QRect(200, 620, 111, 51))
        self.Train.setObjectName("Train")
        self.Walk = QtWidgets.QPushButton(self.centralwidget)
        self.Walk.setGeometry(QtCore.QRect(500, 560, 111, 111))
        self.Walk.setObjectName("Walk")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 500, 591, 41))
        self.label.setText("")
        self.label.setObjectName("label")
        self.knum = QtWidgets.QSpinBox(self.centralwidget)
        self.knum.setGeometry(QtCore.QRect(140, 630, 51, 31))
        self.knum.setMinimum(1)
        self.knum.setMaximum(200)
        self.knum.setProperty("value", 10)
        self.knum.setObjectName("knum")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 640, 21, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(350, 570, 111, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Track = QtWidgets.QPushButton(self.centralwidget)
        self.Track.setGeometry(QtCore.QRect(350, 620, 111, 51))
        self.Track.setObjectName("Track")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 759, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.radio4d.setText(_translate("MainWindow", "train4dAll"))
        self.radio6d.setText(_translate("MainWindow", "train6dAll"))
        self.Train.setText(_translate("MainWindow", "Training"))
        self.Walk.setText(_translate("MainWindow", "Run"))
        self.label_2.setText(_translate("MainWindow", "k:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "track4D.txt"))
        self.comboBox.setItemText(1, _translate("MainWindow", "track6D.txt"))
        self.Track.setText(_translate("MainWindow", "Select Track"))
